namespace MobaGame.Collision
{
    public enum TypedConstraintType
    {
        POINT2POINT_CONSTRAINT_TYPE = 3,
        HINGE_CONSTRAINT_TYPE,
        CONETWIST_CONSTRAINT_TYPE,
        D6_CONSTRAINT_TYPE,
        SLIDER_CONSTRAINT_TYPE,
        CONTACT_CONSTRAINT_TYPE,
        D6_SPRING_CONSTRAINT_TYPE,
        GEAR_CONSTRAINT_TYPE,
        FIXED_CONSTRAINT_TYPE,
        D6_SPRING_2_CONSTRAINT_TYPE,
        MAX_CONSTRAINT_TYPE
    }
}